repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=256", "--extend-ignore=E203,W503,E501"]

  - repo: local
    hooks:
      - id: pyspelling
        name: pyspelling
        entry: pyspelling --config .spellcheck.yml
        language: python
        additional_dependencies: [pyspelling]
        types: [markdown]
        pass_filenames: false
