# .readthedocs.yml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  configuration: docs/conf.py

formats: []

python:
  install:
    - requirements: docs/requirements.txt

