matrix:
- name: Markdown
  sources:
  - '**/*.md'
  - 'CHANGELOG'
  aspell:
    lang: en
    ignore-case: true
  dictionary:
    wordlists:
    - .github/.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  default_encoding: utf-8