"""Base API stubs — shared methods on all Arr API clients."""

from typing import Any, List, Optional

from arrapi.objs.reload import Command, LanguageProfile, QualityProfile, SystemStatus, Tag
from arrapi.objs.simple import RemotePathMapping, RootFolder

class BaseAPI:
    def __init__(self, url: str, apikey: str, **kwargs: Any) -> None: ...
    def all_tags(self, detail: bool = ...) -> List[Tag]: ...
    def get_tag(self, tag_id: int, detail: bool = ...) -> Tag: ...
    def create_tag(self, label: str) -> Tag: ...
    def edit_tag(self, tag_id: int, label: str) -> Tag: ...
    def delete_tag(self, tag_id: int) -> None: ...
    def quality_profile(self) -> List[QualityProfile]: ...
    def root_folder(self) -> List[RootFolder]: ...
    def remote_path_mapping(self) -> List[RemotePathMapping]: ...
    def system_status(self) -> SystemStatus: ...
    def __getattr__(self, name: str) -> Any: ...
