"""Stubs for tmdbapis pagination objects.

TMDbPagination.total_results and get_results() are typed here so that callers
like modules/tmdb.py can use them without union-explosion errors.
"""

from typing import Any, Optional

from tmdbapis.objs.base import TMDbObj

class TMDbPagination(TMDbObj):
    total_results: int
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, index: int) -> Any: ...
    def get_results(self, amount: Optional[int] = ...) -> list[Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class CreatedLists(TMDbPagination): ...
class DiscoverMovies(TMDbPagination): ...
class DiscoverTVShows(TMDbPagination): ...
class FavoriteMovies(TMDbPagination): ...
class FavoriteTVShows(TMDbPagination): ...
class RatedEpisodes(TMDbPagination): ...
class RatedMovies(TMDbPagination): ...
class RatedTVShows(TMDbPagination): ...
class MovieLists(TMDbPagination): ...
class MovieRecommendations(TMDbPagination): ...
class MovieReviews(TMDbPagination): ...
class MovieWatchlist(TMDbPagination): ...
class NowPlayingMovies(TMDbPagination): ...
class PopularMovies(TMDbPagination): ...
class PopularPeople(TMDbPagination): ...
class PopularTVShows(TMDbPagination): ...
class RecommendedMovies(TMDbPagination): ...
class RecommendedTVShows(TMDbPagination): ...
class SearchCompanies(TMDbPagination): ...
class SearchCollections(TMDbPagination): ...
class SearchKeywords(TMDbPagination): ...
class SearchMovies(TMDbPagination): ...
class SearchMulti(TMDbPagination): ...
class SearchPeople(TMDbPagination): ...
class SearchTVShows(TMDbPagination): ...
class SimilarMovies(TMDbPagination): ...
class SimilarTVShows(TMDbPagination): ...
class TaggedImages(TMDbPagination): ...
class TopRatedMovies(TMDbPagination): ...
class TopRatedTVShows(TMDbPagination): ...
class TrendingAll(TMDbPagination): ...
class TrendingMovies(TMDbPagination): ...
class TrendingPeople(TMDbPagination): ...
class TrendingTVShows(TMDbPagination): ...
class TVShowWatchlist(TMDbPagination): ...
class TVAiringToday(TMDbPagination): ...
class TVOnAir(TMDbPagination): ...
class UpcomingMovies(TMDbPagination): ...
