class ArrException(Exception): ...
class ConnectionFailure(ArrException): ...
class Excluded(ArrException): ...
class Exists(ArrException): ...
class Invalid(ArrException): ...
class NotFound(ArrException): ...
class Unauthorized(ArrException): ...
