name: Wiki Issue
description: A request to update or improve Plex Meta Manager's wiki
labels: ['status:not-yet-viewed', 'documentation']
assignees: 'meisnate12'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR FEATURE REQUESTS!**
        Please use [Plex Meta Manager Discord](https://metamanager.wiki/en/latest/discord/) and post your question under the `pmm-support` channel for support issues.
        Please use [Plex Meta Manager Features](https://features.metamanager.wiki/) to request and upvote features.
  - type: textarea
    attributes:
      label: What is the improvement or update to the Wiki you wish to see?
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Example: https://metamanager.wiki/en/latest/config/operations.html'
    validations:
      required: false