from typing import Any

from tmdbapis.objs.base import TMDbObj

class TMDbImage(TMDbObj):
    def __getattr__(self, name: str) -> Any: ...

class Backdrop(TMDbImage): ...
class Logo(TMDbImage): ...
class Poster(TMDbImage): ...
class Profile(TMDbImage): ...
class Still(TMDbImage): ...
class Tagged(TMDbImage): ...
