authors:
  yozora:
    name: Yozora
    description: Moderator
    avatar: https://avatars.githubusercontent.com/u/96386153?v=4
  sohjiro:
    name: Sohjiro
    description: Founder
    avatar: https://avatars.githubusercontent.com/u/1631064?v=4
  chaz:
    name: Chaz Larson
    description: Moderator
    avatar: https://avatars.githubusercontent.com/u/3865541?v=4
  bullmoose:
    name: Bullmoose
    description: Moderator
    avatar: https://avatars.githubusercontent.com/u/12549033?v=4