name: Release Notification

on:
  release:
    types: [ published ]

jobs:

  release-notification:

    runs-on: ubuntu-latest
    steps:

      - name: Send Discord Release Notification
        uses: Kometa-Team/discord-notifications@master
        with:
          webhook_id_token: ${{ secrets.RELEASE_WEBHOOK }}
          release: true
          title: Release VERSION
          message: "${{ vars.MASTER_ROLE }} - A new version of ${{ vars.NAME }} has been released and is available to all users.\n\nWe **strongly** recommend users who previously switched to the `nightly` or `develop` branches to resolve any previous issues to now switch back to the `latest` branch now."
          color: ${{ vars.COLOR_SUCCESS }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.NAME }} Release
          author_icon_url: ${{ vars.RELEASE_IMAGE }}