name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
    # The checkout step
    - uses: actions/checkout@v7
    - uses: rojopolis/spellcheck-github-actions@0.64.0
      name: Spellcheck 