name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v6
    - uses: rojopolis/spellcheck-github-actions@0.62.0
      name: Spellcheck 