name: Tag New Version

on:
  push:
    branches: [ master ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 2

      - uses: Kometa-Team/tag-new-version@1dd1fb186f3f5229331e8ddf6515288633a2412e # master
        with:
          version-command: |
            cat VERSION